LitJson::JsonReader
IDictionary<int, IDictionary<int, int[]> > LitJson.JsonReader.parse_table
Referenced by LitJson.JsonReader.PopulateParseTable, LitJson.JsonReader.Read, LitJson.JsonReader.TableAddCol.
Stack<int> LitJson.JsonReader.automaton_stack
Referenced by LitJson.JsonReader.JsonReader, LitJson.JsonReader.Read.
int LitJson.JsonReader.current_input
Referenced by LitJson.JsonReader.Read, LitJson.JsonReader.ReadToken.
int LitJson.JsonReader.current_symbol
Referenced by LitJson.JsonReader.ProcessSymbol, LitJson.JsonReader.Read.
bool LitJson.JsonReader.end_of_json
Referenced by LitJson.JsonReader.Close, LitJson.JsonReader.JsonReader, LitJson.JsonReader.Read.
bool LitJson.JsonReader.end_of_input
Referenced by LitJson.JsonReader.Close, LitJson.JsonReader.JsonReader, LitJson.JsonReader.Read, LitJson.JsonReader.ReadToken.
Lexer LitJson.JsonReader.lexer
Referenced by LitJson.JsonReader.JsonReader, LitJson.JsonReader.ProcessSymbol, LitJson.JsonReader.ReadToken.
bool LitJson.JsonReader.parser_in_string
Referenced by LitJson.JsonReader.JsonReader, LitJson.JsonReader.ProcessSymbol, LitJson.JsonReader.Read.
bool LitJson.JsonReader.parser_return
Referenced by LitJson.JsonReader.JsonReader, LitJson.JsonReader.ProcessSymbol, LitJson.JsonReader.Read.
bool LitJson.JsonReader.read_started
Referenced by LitJson.JsonReader.JsonReader, LitJson.JsonReader.Read.
TextReader LitJson.JsonReader.reader
Referenced by LitJson.JsonReader.Close, LitJson.JsonReader.JsonReader.
bool LitJson.JsonReader.reader_is_owned
Referenced by LitJson.JsonReader.Close, LitJson.JsonReader.JsonReader.
bool LitJson.JsonReader.skip_non_members
Referenced by LitJson.JsonReader.JsonReader.
object LitJson.JsonReader.token_value
Referenced by LitJson.JsonReader.ProcessNumber, LitJson.JsonReader.ProcessSymbol, LitJson.JsonReader.Read.
JsonToken LitJson.JsonReader.token
Referenced by LitJson.JsonReader.ProcessNumber, LitJson.JsonReader.ProcessSymbol, LitJson.JsonReader.Read.
bool LitJson.JsonReader.AllowComments
bool LitJson.JsonReader.AllowSingleQuotedStrings
bool LitJson.JsonReader.SkipNonMembers
Referenced by LitJson.JsonMapper.ReadValue.
bool LitJson.JsonReader.EndOfInput
bool LitJson.JsonReader.EndOfJson
JsonToken LitJson.JsonReader.Token
Referenced by LitJson.JsonMapper.ReadValue.
object LitJson.JsonReader.Value
Referenced by LitJson.JsonMapper.ReadValue.
static LitJson.JsonReader.JsonReader()
References LitJson.JsonReader.PopulateParseTable.
static void LitJson.JsonReader.PopulateParseTable()
References LitJson.JsonReader.parse_table, LitJson.JsonReader.TableAddCol, LitJson.JsonReader.TableAddRow.
Referenced by LitJson.JsonReader.JsonReader.
static void LitJson.JsonReader.TableAddCol(ParserToken row, int col, params int[] symbols)
References LitJson.JsonReader.parse_table.
Referenced by LitJson.JsonReader.PopulateParseTable.
static void LitJson.JsonReader.TableAddRow(ParserToken rule)
Referenced by LitJson.JsonReader.PopulateParseTable.
LitJson.JsonReader.JsonReader(string json_text)
LitJson.JsonReader.JsonReader(TextReader reader)
void LitJson.JsonReader.Close()
References LitJson.JsonReader.end_of_input, LitJson.JsonReader.end_of_json, LitJson.JsonReader.reader, LitJson.JsonReader.reader_is_owned.
Referenced by LitJson.JsonReader.ReadToken.
bool LitJson.JsonReader.Read()
References LitJson.JsonReader.automaton_stack, LitJson.JsonReader.current_input, LitJson.JsonReader.current_symbol, LitJson.JsonReader.end_of_input, LitJson.JsonReader.end_of_json, LitJson.JsonReader.parse_table, LitJson.JsonReader.parser_in_string, LitJson.JsonReader.parser_return, LitJson.JsonReader.ProcessSymbol, LitJson.JsonReader.read_started, LitJson.JsonReader.ReadToken, LitJson.JsonReader.token, LitJson.JsonReader.token_value.
LitJson.JsonReader.JsonReader(TextReader reader, bool owned)
References LitJson.JsonReader.automaton_stack, LitJson.JsonReader.end_of_input, LitJson.JsonReader.end_of_json, LitJson.JsonReader.lexer, LitJson.JsonReader.parser_in_string, LitJson.JsonReader.parser_return, LitJson.JsonReader.read_started, LitJson.JsonReader.reader, LitJson.JsonReader.reader_is_owned, LitJson.JsonReader.skip_non_members.
void LitJson.JsonReader.ProcessNumber(string number)
References LitJson.Double, LitJson.JsonReader.token, LitJson.JsonReader.token_value.
Referenced by LitJson.JsonReader.ProcessSymbol.
void LitJson.JsonReader.ProcessSymbol()
References LitJson.JsonReader.current_symbol, LitJson.JsonReader.lexer, LitJson.JsonReader.parser_in_string, LitJson.JsonReader.parser_return, LitJson.JsonReader.ProcessNumber, LitJson.Lexer.StringValue, LitJson.JsonReader.token, LitJson.JsonReader.token_value.
Referenced by LitJson.JsonReader.Read.
bool LitJson.JsonReader.ReadToken()
References LitJson.JsonReader.Close, LitJson.JsonReader.current_input, LitJson.JsonReader.end_of_input, LitJson.Lexer.EndOfInput, LitJson.JsonReader.lexer.
Referenced by LitJson.JsonReader.Read.