LitFramework::AudioManager
Func<string , AudioClip> LitFramework.AudioManager.LoadResourceFunc
Referenced by LitFramework.AudioManager.LoadAudio, LitFramework.AudioManager.Uninstall.
string LitFramework.AudioManager.currentMusicName
Referenced by LitFramework.AudioManager.PlayBGM.
float LitFramework.AudioManager.VolumeSE
Referenced by LitFramework.AudioManager.Install, LitFramework.AudioManager.OnSEValumeChange, LitFramework.AudioManager.PlaySE, LitFramework.AudioManager.PlaySoloSE.
float LitFramework.AudioManager.VolumeBGM
Referenced by LitFramework.AudioManager.Install, LitFramework.AudioManager.OnBGMValumeChange, LitFramework.AudioManager.PlayBGM.
List<AudioSource> LitFramework.AudioManager._tempList
Referenced by LitFramework.AudioManager.Install, LitFramework.AudioManager.PlaySE, LitFramework.AudioManager.Uninstall.
AudioSource LitFramework.AudioManager._audioBGM
Referenced by LitFramework.AudioManager.Install, LitFramework.AudioManager.PauseBGM, LitFramework.AudioManager.ResumeBGM, LitFramework.AudioManager.StopBGM, LitFramework.AudioManager.Uninstall.
AudioSource LitFramework.AudioManager._soloAudioSource
Referenced by LitFramework.AudioManager.Install, LitFramework.AudioManager.PlaySoloSE, LitFramework.AudioManager.Uninstall.
Stack<AudioSource> LitFramework.AudioManager._soundAvalibleList
Referenced by LitFramework.AudioManager.Install, LitFramework.AudioManager.PlaySE, LitFramework.AudioManager.StopAllSE, LitFramework.AudioManager.Uninstall.
Dictionary<string , AudioClip> LitFramework.AudioManager._audios
Referenced by LitFramework.AudioManager.GetBGM, LitFramework.AudioManager.GetSE, LitFramework.AudioManager.Install, LitFramework.AudioManager.LoadAudio, LitFramework.AudioManager.Uninstall.
Dictionary<string , AudioSource> LitFramework.AudioManager._soundLoopPlayingDict
Referenced by LitFramework.AudioManager.Install, LitFramework.AudioManager.PlaySE, LitFramework.AudioManager.StopAllSE, LitFramework.AudioManager.StopSE, LitFramework.AudioManager.Uninstall.
void LitFramework.AudioManager.Install()
启动音频模块
loadFunction 提供音频加载方法
References LitFramework.AudioManager._audioBGM, LitFramework.AudioManager._audios, LitFramework.AudioManager._soloAudioSource, LitFramework.AudioManager._soundAvalibleList, LitFramework.AudioManager._soundLoopPlayingDict, LitFramework.AudioManager._tempList, LitFramework.AudioManager.VolumeBGM, LitFramework.AudioManager.VolumeSE.
void LitFramework.AudioManager.Uninstall()
卸载模块
References LitFramework.AudioManager._audioBGM, LitFramework.AudioManager._audios, LitFramework.AudioManager._soloAudioSource, LitFramework.AudioManager._soundAvalibleList, LitFramework.AudioManager._soundLoopPlayingDict, LitFramework.AudioManager._tempList, LitFramework.AudioManager.LoadResourceFunc, LitFramework.AudioManager.StopAllSE.
AudioClip LitFramework.AudioManager.GetBGM(string name)
获取音乐
name
References LitFramework.AudioManager._audios, LitFramework.AudioManager.LoadAudio.
Referenced by LitFramework.AudioManager.PlayBGM.
AudioClip LitFramework.AudioManager.GetSE(string name)
获取音效
name
References LitFramework.AudioManager._audios, LitFramework.AudioManager.LoadAudio.
Referenced by LitFramework.AudioManager.PlaySE, LitFramework.AudioManager.PlaySoloSE.
void LitFramework.AudioManager.PlaySE(string name, bool loop=false, bool isParallel=true, float volumeRate=1f)
播放音效 修改： 用栈管理多个音效组件，处理同时存在的多个持续存在的声音效果
name 名称
References LitFramework.AudioManager._soundAvalibleList, LitFramework.AudioManager._soundLoopPlayingDict, LitFramework.AudioManager._tempList, LitFramework.AudioManager.GetSE, LitFramework.AudioManager.VolumeSE.
void LitFramework.AudioManager.StopSE(string name)
停止持续播放的音效 只针对loop声效有效
name
References LitFramework.AudioManager._soundLoopPlayingDict.
Referenced by LitFramework.AudioManager.StopAllSE.
void LitFramework.AudioManager.StopAllSE()
关闭全部音效
References LitFramework.AudioManager._soundAvalibleList, LitFramework.AudioManager._soundLoopPlayingDict, LitFramework.AudioManager.StopSE.
Referenced by LitFramework.AudioManager.Uninstall.
void LitFramework.AudioManager.PlayBGM(string name, bool loop=true)
播放音乐
name loop
References LitFramework.AudioManager.currentMusicName, LitFramework.AudioManager.GetBGM, LitFramework.AudioManager.VolumeBGM.
void LitFramework.AudioManager.PauseBGM()
暂停音乐
References LitFramework.AudioManager._audioBGM.
void LitFramework.AudioManager.StopBGM()
停止音乐
References LitFramework.AudioManager._audioBGM.
void LitFramework.AudioManager.ResumeBGM()
继续播放音乐
References LitFramework.AudioManager._audioBGM.
void LitFramework.AudioManager.OnBGMValumeChange(float vol)
侦听音量改变
vol
References LitFramework.AudioManager.VolumeBGM.
void LitFramework.AudioManager.OnSEValumeChange(float vol)
侦听音乐改变
vol
References LitFramework.AudioManager.VolumeSE.
void LitFramework.AudioManager.PlaySoloSE(string name)
播放独立音效，单次且不可覆盖播放
name
References LitFramework.AudioManager._soloAudioSource, LitFramework.AudioManager.GetSE, LitFramework.AudioManager.VolumeSE.
void LitFramework.AudioManager.LoadAudio(string name)
References LitFramework.AudioManager._audios, LitFramework.AudioManager.LoadResourceFunc.
Referenced by LitFramework.AudioManager.GetBGM, LitFramework.AudioManager.GetSE.