LitJson::JsonWriter
NumberFormatInfo LitJson.JsonWriter.number_format
Referenced by LitJson.JsonWriter.JsonWriter, LitJson.JsonWriter.Write.
WriterContext LitJson.JsonWriter.context
Referenced by LitJson.JsonWriter.DoValidation, LitJson.JsonWriter.Init, LitJson.JsonWriter.Put, LitJson.JsonWriter.PutNewline, LitJson.JsonWriter.Reset, LitJson.JsonWriter.WriteArrayEnd, LitJson.JsonWriter.WriteArrayStart, LitJson.JsonWriter.WriteObjectEnd, LitJson.JsonWriter.WriteObjectStart, LitJson.JsonWriter.WritePropertyName.
Stack<WriterContext> LitJson.JsonWriter.ctx_stack
Referenced by LitJson.JsonWriter.Init, LitJson.JsonWriter.WriteArrayEnd, LitJson.JsonWriter.WriteObjectEnd.
bool LitJson.JsonWriter.has_reached_end
Referenced by LitJson.JsonWriter.DoValidation, LitJson.JsonWriter.Init, LitJson.JsonWriter.Reset, LitJson.JsonWriter.WriteArrayEnd, LitJson.JsonWriter.WriteObjectEnd.
char [] LitJson.JsonWriter.hex_seq
Referenced by LitJson.JsonWriter.Init, LitJson.JsonWriter.PutString.
int LitJson.JsonWriter.indentation
Referenced by LitJson.JsonWriter.Indent, LitJson.JsonWriter.Init, LitJson.JsonWriter.Put, LitJson.JsonWriter.Unindent.
int LitJson.JsonWriter.indent_value
Referenced by LitJson.JsonWriter.Indent, LitJson.JsonWriter.Init, LitJson.JsonWriter.Unindent.
StringBuilder LitJson.JsonWriter.inst_string_builder
Referenced by LitJson.JsonWriter.JsonWriter, LitJson.JsonWriter.Reset, LitJson.JsonWriter.ToString.
bool LitJson.JsonWriter.pretty_print
Referenced by LitJson.JsonWriter.Indent, LitJson.JsonWriter.Init, LitJson.JsonWriter.Put, LitJson.JsonWriter.PutNewline, LitJson.JsonWriter.Unindent, LitJson.JsonWriter.WritePropertyName.
bool LitJson.JsonWriter.validate
Referenced by LitJson.JsonWriter.DoValidation, LitJson.JsonWriter.Init.
TextWriter LitJson.JsonWriter.writer
Referenced by LitJson.JsonWriter.JsonWriter, LitJson.JsonWriter.Put.
int LitJson.JsonWriter.IndentValue
bool LitJson.JsonWriter.PrettyPrint
TextWriter LitJson.JsonWriter.TextWriter
bool LitJson.JsonWriter.Validate
static LitJson.JsonWriter.JsonWriter()
References LitJson.JsonWriter.number_format.
static void LitJson.JsonWriter.IntToHex(int n, char[] hex)
Referenced by LitJson.JsonWriter.PutString.
LitJson.JsonWriter.JsonWriter()
References LitJson.JsonWriter.Init, LitJson.JsonWriter.inst_string_builder, LitJson.JsonWriter.writer.
LitJson.JsonWriter.JsonWriter(StringBuilder sb)
LitJson.JsonWriter.JsonWriter(TextWriter writer)
References LitJson.JsonWriter.Init, LitJson.JsonWriter.writer.
override string LitJson.JsonWriter.ToString()
References LitJson.JsonWriter.inst_string_builder.
void LitJson.JsonWriter.Reset()
References LitJson.JsonWriter.context, LitJson.JsonWriter.has_reached_end, LitJson.JsonWriter.inst_string_builder.
void LitJson.JsonWriter.Write(bool boolean)
References LitJson.JsonWriter.DoValidation, LitJson.JsonWriter.Put, LitJson.JsonWriter.PutNewline.
Referenced by LitJson.JsonMapper.WriteValue.
void LitJson.JsonWriter.Write(decimal number)
References LitJson.JsonWriter.DoValidation, LitJson.JsonWriter.number_format, LitJson.JsonWriter.Put, LitJson.JsonWriter.PutNewline.
void LitJson.JsonWriter.Write(double number)
References LitJson.JsonWriter.DoValidation, LitJson.JsonWriter.number_format, LitJson.JsonWriter.Put, LitJson.JsonWriter.PutNewline.
void LitJson.JsonWriter.Write(int number)
References LitJson.JsonWriter.DoValidation, LitJson.JsonWriter.number_format, LitJson.JsonWriter.Put, LitJson.JsonWriter.PutNewline.
void LitJson.JsonWriter.Write(long number)
References LitJson.JsonWriter.DoValidation, LitJson.JsonWriter.number_format, LitJson.JsonWriter.Put, LitJson.JsonWriter.PutNewline.
void LitJson.JsonWriter.Write(string str)
References LitJson.JsonWriter.DoValidation, LitJson.JsonWriter.Put, LitJson.JsonWriter.PutNewline, LitJson.JsonWriter.PutString.
void LitJson.JsonWriter.Write(ulong number)
References LitJson.JsonWriter.DoValidation, LitJson.JsonWriter.number_format, LitJson.JsonWriter.Put, LitJson.JsonWriter.PutNewline.
void LitJson.JsonWriter.WriteArrayEnd()
References LitJson.JsonWriter.context, LitJson.JsonWriter.ctx_stack, LitJson.JsonWriter.DoValidation, LitJson.JsonWriter.has_reached_end, LitJson.JsonWriter.Put, LitJson.JsonWriter.PutNewline, LitJson.JsonWriter.Unindent.
void LitJson.JsonWriter.WriteArrayStart()
References LitJson.JsonWriter.context, LitJson.JsonWriter.DoValidation, LitJson.JsonWriter.Indent, LitJson.JsonWriter.Put, LitJson.JsonWriter.PutNewline.
void LitJson.JsonWriter.WriteObjectEnd()
References LitJson.JsonWriter.context, LitJson.JsonWriter.ctx_stack, LitJson.JsonWriter.DoValidation, LitJson.JsonWriter.has_reached_end, LitJson.JsonWriter.Put, LitJson.JsonWriter.PutNewline, LitJson.JsonWriter.Unindent.
void LitJson.JsonWriter.WriteObjectStart()
References LitJson.JsonWriter.context, LitJson.JsonWriter.DoValidation, LitJson.JsonWriter.Indent, LitJson.JsonWriter.Put, LitJson.JsonWriter.PutNewline.
void LitJson.JsonWriter.WritePropertyName(string property_name)
References LitJson.JsonWriter.context, LitJson.JsonWriter.DoValidation, LitJson.WriterContext.Padding, LitJson.JsonWriter.pretty_print, LitJson.JsonWriter.PutNewline, LitJson.JsonWriter.PutString.
void LitJson.JsonWriter.DoValidation(Condition cond)
References LitJson.JsonWriter.context, LitJson.WriterContext.ExpectingValue, LitJson.JsonWriter.has_reached_end, LitJson.WriterContext.InArray, LitJson.WriterContext.InObject, LitJson.JsonWriter.validate.
Referenced by LitJson.JsonWriter.Write, LitJson.JsonWriter.WriteArrayEnd, LitJson.JsonWriter.WriteArrayStart, LitJson.JsonWriter.WriteObjectEnd, LitJson.JsonWriter.WriteObjectStart, LitJson.JsonWriter.WritePropertyName.
void LitJson.JsonWriter.Init()
References LitJson.JsonWriter.context, LitJson.JsonWriter.ctx_stack, LitJson.JsonWriter.has_reached_end, LitJson.JsonWriter.hex_seq, LitJson.JsonWriter.indent_value, LitJson.JsonWriter.indentation, LitJson.JsonWriter.pretty_print, LitJson.JsonWriter.validate.
Referenced by LitJson.JsonWriter.JsonWriter.
void LitJson.JsonWriter.Indent()
References LitJson.JsonWriter.indent_value, LitJson.JsonWriter.indentation, LitJson.JsonWriter.pretty_print.
Referenced by LitJson.JsonWriter.WriteArrayStart, LitJson.JsonWriter.WriteObjectStart.
void LitJson.JsonWriter.Put(string str)
References LitJson.JsonWriter.context, LitJson.WriterContext.ExpectingValue, LitJson.JsonWriter.indentation, LitJson.JsonWriter.pretty_print, LitJson.JsonWriter.writer.
Referenced by LitJson.JsonWriter.PutString, LitJson.JsonWriter.Write, LitJson.JsonWriter.WriteArrayEnd, LitJson.JsonWriter.WriteArrayStart, LitJson.JsonWriter.WriteObjectEnd, LitJson.JsonWriter.WriteObjectStart.
void LitJson.JsonWriter.PutNewline()
Referenced by LitJson.JsonWriter.Write, LitJson.JsonWriter.WriteArrayEnd, LitJson.JsonWriter.WriteArrayStart, LitJson.JsonWriter.WriteObjectEnd, LitJson.JsonWriter.WriteObjectStart, LitJson.JsonWriter.WritePropertyName.
void LitJson.JsonWriter.PutNewline(bool add_comma)
References LitJson.JsonWriter.context, LitJson.WriterContext.Count, LitJson.WriterContext.ExpectingValue, LitJson.JsonWriter.pretty_print.
void LitJson.JsonWriter.PutString(string str)
References LitJson.JsonWriter.hex_seq, LitJson.JsonWriter.IntToHex, LitJson.JsonWriter.Put, LitJson.String.
Referenced by LitJson.JsonWriter.Write, LitJson.JsonWriter.WritePropertyName.
void LitJson.JsonWriter.Unindent()
References LitJson.JsonWriter.indent_value, LitJson.JsonWriter.indentation, LitJson.JsonWriter.pretty_print.
Referenced by LitJson.JsonWriter.WriteArrayEnd, LitJson.JsonWriter.WriteObjectEnd.