LitJson::Lexer
int [] LitJson.Lexer.fsm_return_table
Referenced by LitJson.Lexer.NextToken, LitJson.Lexer.PopulateFsmTables.
StateHandler [] LitJson.Lexer.fsm_handler_table
Referenced by LitJson.Lexer.NextToken, LitJson.Lexer.PopulateFsmTables.
bool LitJson.Lexer.allow_comments
Referenced by LitJson.Lexer.Lexer, LitJson.Lexer.State1.
bool LitJson.Lexer.allow_single_quoted_strings
Referenced by LitJson.Lexer.Lexer, LitJson.Lexer.State1.
bool LitJson.Lexer.end_of_input
Referenced by LitJson.Lexer.GetChar, LitJson.Lexer.Lexer, LitJson.Lexer.NextToken.
FsmContext LitJson.Lexer.fsm_context
Referenced by LitJson.Lexer.Lexer, LitJson.Lexer.NextToken.
int LitJson.Lexer.input_buffer
Referenced by LitJson.Lexer.Lexer, LitJson.Lexer.NextChar, LitJson.Lexer.UngetChar.
int LitJson.Lexer.input_char
Referenced by LitJson.Lexer.GetChar, LitJson.Lexer.NextToken, LitJson.Lexer.State1, LitJson.Lexer.State10, LitJson.Lexer.State11, LitJson.Lexer.State12, LitJson.Lexer.State13, LitJson.Lexer.State14, LitJson.Lexer.State15, LitJson.Lexer.State16, LitJson.Lexer.State17, LitJson.Lexer.State18, LitJson.Lexer.State19, LitJson.Lexer.State2, LitJson.Lexer.State20, LitJson.Lexer.State21, LitJson.Lexer.State22, LitJson.Lexer.State23, LitJson.Lexer.State24, LitJson.Lexer.State25, LitJson.Lexer.State26, LitJson.Lexer.State27, LitJson.Lexer.State28, LitJson.Lexer.State3, LitJson.Lexer.State4, LitJson.Lexer.State5, LitJson.Lexer.State6, LitJson.Lexer.State7, LitJson.Lexer.State8, LitJson.Lexer.State9, LitJson.Lexer.UngetChar.
TextReader LitJson.Lexer.reader
Referenced by LitJson.Lexer.Lexer.
int LitJson.Lexer.state
Referenced by LitJson.Lexer.Lexer, LitJson.Lexer.NextToken.
StringBuilder LitJson.Lexer.string_buffer
Referenced by LitJson.Lexer.Lexer.
string LitJson.Lexer.string_value
Referenced by LitJson.Lexer.NextToken.
int LitJson.Lexer.token
Referenced by LitJson.Lexer.NextToken.
int LitJson.Lexer.unichar
bool LitJson.Lexer.AllowComments
bool LitJson.Lexer.AllowSingleQuotedStrings
bool LitJson.Lexer.EndOfInput
Referenced by LitJson.JsonReader.ReadToken.
int LitJson.Lexer.Token
string LitJson.Lexer.StringValue
Referenced by LitJson.JsonReader.ProcessSymbol.
delegate bool LitJson.Lexer.StateHandler(FsmContext ctx)
bool LitJson.Lexer.GetChar()
References LitJson.Lexer.end_of_input, LitJson.Lexer.input_char, LitJson.Lexer.NextChar.
Referenced by LitJson.Lexer.State1, LitJson.Lexer.State19, LitJson.Lexer.State22, LitJson.Lexer.State23, LitJson.Lexer.State26, LitJson.Lexer.State27, LitJson.Lexer.State28, LitJson.Lexer.State3, LitJson.Lexer.State6, LitJson.Lexer.State8.
int LitJson.Lexer.NextChar()
References LitJson.Lexer.input_buffer.
Referenced by LitJson.Lexer.GetChar.
void LitJson.Lexer.UngetChar()
References LitJson.Lexer.input_buffer, LitJson.Lexer.input_char.
static LitJson.Lexer.Lexer()
References LitJson.Lexer.PopulateFsmTables.
static int LitJson.Lexer.HexValue(int digit)
Referenced by LitJson.Lexer.State22.
static void LitJson.Lexer.PopulateFsmTables()
References LitJson.Lexer.fsm_handler_table, LitJson.Lexer.fsm_return_table, LitJson.Lexer.State1, LitJson.Lexer.State10, LitJson.Lexer.State11, LitJson.Lexer.State12, LitJson.Lexer.State13, LitJson.Lexer.State14, LitJson.Lexer.State15, LitJson.Lexer.State16, LitJson.Lexer.State17, LitJson.Lexer.State18, LitJson.Lexer.State19, LitJson.Lexer.State2, LitJson.Lexer.State20, LitJson.Lexer.State21, LitJson.Lexer.State22, LitJson.Lexer.State23, LitJson.Lexer.State24, LitJson.Lexer.State25, LitJson.Lexer.State26, LitJson.Lexer.State27, LitJson.Lexer.State28, LitJson.Lexer.State3, LitJson.Lexer.State4, LitJson.Lexer.State5, LitJson.Lexer.State6, LitJson.Lexer.State7, LitJson.Lexer.State8, LitJson.Lexer.State9.
Referenced by LitJson.Lexer.Lexer.
static char LitJson.Lexer.ProcessEscChar(int esc_char)
Referenced by LitJson.Lexer.State21.
static bool LitJson.Lexer.State1(FsmContext ctx)
References LitJson.Lexer.allow_comments, LitJson.Lexer.allow_single_quoted_strings, LitJson.Lexer.GetChar, LitJson.Lexer.input_char, LitJson.FsmContext.L.
Referenced by LitJson.Lexer.PopulateFsmTables.
static bool LitJson.Lexer.State2(FsmContext ctx)
References LitJson.Lexer.input_char, LitJson.FsmContext.L.
Referenced by LitJson.Lexer.PopulateFsmTables.
static bool LitJson.Lexer.State3(FsmContext ctx)
References LitJson.Lexer.GetChar, LitJson.Lexer.input_char, LitJson.FsmContext.L.
Referenced by LitJson.Lexer.PopulateFsmTables.
static bool LitJson.Lexer.State4(FsmContext ctx)
References LitJson.Lexer.input_char, LitJson.FsmContext.L.
Referenced by LitJson.Lexer.PopulateFsmTables.
static bool LitJson.Lexer.State5(FsmContext ctx)
References LitJson.Lexer.input_char, LitJson.FsmContext.L.
Referenced by LitJson.Lexer.PopulateFsmTables.
static bool LitJson.Lexer.State6(FsmContext ctx)
References LitJson.Lexer.GetChar, LitJson.Lexer.input_char, LitJson.FsmContext.L.
Referenced by LitJson.Lexer.PopulateFsmTables.
static bool LitJson.Lexer.State7(FsmContext ctx)
References LitJson.Lexer.input_char, LitJson.FsmContext.L.
Referenced by LitJson.Lexer.PopulateFsmTables.
static bool LitJson.Lexer.State8(FsmContext ctx)
References LitJson.Lexer.GetChar, LitJson.Lexer.input_char, LitJson.FsmContext.L.
Referenced by LitJson.Lexer.PopulateFsmTables.
static bool LitJson.Lexer.State9(FsmContext ctx)
References LitJson.Lexer.input_char, LitJson.FsmContext.L.
Referenced by LitJson.Lexer.PopulateFsmTables.
static bool LitJson.Lexer.State10(FsmContext ctx)
References LitJson.Lexer.input_char, LitJson.FsmContext.L.
Referenced by LitJson.Lexer.PopulateFsmTables.
static bool LitJson.Lexer.State11(FsmContext ctx)
References LitJson.Lexer.input_char, LitJson.FsmContext.L.
Referenced by LitJson.Lexer.PopulateFsmTables.
static bool LitJson.Lexer.State12(FsmContext ctx)
References LitJson.Lexer.input_char, LitJson.FsmContext.L.
Referenced by LitJson.Lexer.PopulateFsmTables.
static bool LitJson.Lexer.State13(FsmContext ctx)
References LitJson.Lexer.input_char, LitJson.FsmContext.L.
Referenced by LitJson.Lexer.PopulateFsmTables.
static bool LitJson.Lexer.State14(FsmContext ctx)
References LitJson.Lexer.input_char, LitJson.FsmContext.L.
Referenced by LitJson.Lexer.PopulateFsmTables.
static bool LitJson.Lexer.State15(FsmContext ctx)
References LitJson.Lexer.input_char, LitJson.FsmContext.L.
Referenced by LitJson.Lexer.PopulateFsmTables.
static bool LitJson.Lexer.State16(FsmContext ctx)
References LitJson.Lexer.input_char, LitJson.FsmContext.L.
Referenced by LitJson.Lexer.PopulateFsmTables.
static bool LitJson.Lexer.State17(FsmContext ctx)
References LitJson.Lexer.input_char, LitJson.FsmContext.L.
Referenced by LitJson.Lexer.PopulateFsmTables.
static bool LitJson.Lexer.State18(FsmContext ctx)
References LitJson.Lexer.input_char, LitJson.FsmContext.L.
Referenced by LitJson.Lexer.PopulateFsmTables.
static bool LitJson.Lexer.State19(FsmContext ctx)
References LitJson.Lexer.GetChar, LitJson.Lexer.input_char, LitJson.FsmContext.L.
Referenced by LitJson.Lexer.PopulateFsmTables.
static bool LitJson.Lexer.State20(FsmContext ctx)
References LitJson.Lexer.input_char, LitJson.FsmContext.L.
Referenced by LitJson.Lexer.PopulateFsmTables.
static bool LitJson.Lexer.State21(FsmContext ctx)
References LitJson.Lexer.input_char, LitJson.FsmContext.L, LitJson.Lexer.ProcessEscChar.
Referenced by LitJson.Lexer.PopulateFsmTables.
static bool LitJson.Lexer.State22(FsmContext ctx)
References LitJson.Lexer.GetChar, LitJson.Lexer.HexValue, LitJson.Lexer.input_char, LitJson.FsmContext.L.
Referenced by LitJson.Lexer.PopulateFsmTables.
static bool LitJson.Lexer.State23(FsmContext ctx)
References LitJson.Lexer.GetChar, LitJson.Lexer.input_char, LitJson.FsmContext.L.
Referenced by LitJson.Lexer.PopulateFsmTables.
static bool LitJson.Lexer.State24(FsmContext ctx)
References LitJson.Lexer.input_char, LitJson.FsmContext.L.
Referenced by LitJson.Lexer.PopulateFsmTables.
static bool LitJson.Lexer.State25(FsmContext ctx)
References LitJson.Lexer.input_char, LitJson.FsmContext.L.
Referenced by LitJson.Lexer.PopulateFsmTables.
static bool LitJson.Lexer.State26(FsmContext ctx)
References LitJson.Lexer.GetChar, LitJson.Lexer.input_char, LitJson.FsmContext.L.
Referenced by LitJson.Lexer.PopulateFsmTables.
static bool LitJson.Lexer.State27(FsmContext ctx)
References LitJson.Lexer.GetChar, LitJson.Lexer.input_char, LitJson.FsmContext.L.
Referenced by LitJson.Lexer.PopulateFsmTables.
static bool LitJson.Lexer.State28(FsmContext ctx)
References LitJson.Lexer.GetChar, LitJson.Lexer.input_char, LitJson.FsmContext.L.
Referenced by LitJson.Lexer.PopulateFsmTables.
LitJson.Lexer.Lexer(TextReader reader)
References LitJson.Lexer.allow_comments, LitJson.Lexer.allow_single_quoted_strings, LitJson.Lexer.end_of_input, LitJson.Lexer.fsm_context, LitJson.Lexer.input_buffer, LitJson.Lexer.reader, LitJson.Lexer.state, LitJson.Lexer.string_buffer.
bool LitJson.Lexer.NextToken()
References LitJson.Lexer.end_of_input, LitJson.Lexer.fsm_context, LitJson.Lexer.fsm_handler_table, LitJson.Lexer.fsm_return_table, LitJson.Lexer.input_char, LitJson.FsmContext.Return, LitJson.Lexer.state, LitJson.Lexer.string_value, LitJson.Lexer.token.