PathologicalGames::SpawnPoolsDict
Dictionary<string , OnCreatedDelegate> PathologicalGames.SpawnPoolsDict.onCreatedDelegates
Referenced by PathologicalGames.SpawnPoolsDict.Add, PathologicalGames.SpawnPoolsDict.AddOnCreatedDelegate, PathologicalGames.SpawnPoolsDict.RemoveOnCreatedDelegate.
Dictionary<string , SpawnPool> PathologicalGames.SpawnPoolsDict._pools
Referenced by PathologicalGames.SpawnPoolsDict.Destroy, PathologicalGames.SpawnPoolsDict.DestroyAll.
int PathologicalGames.SpawnPoolsDict.Count
Get the number of SpawnPools in PoolManager
SpawnPool PathologicalGames.SpawnPoolsDict.this[string key]
ICollection<string> PathologicalGames.SpawnPoolsDict.Keys
ICollection<SpawnPool> PathologicalGames.SpawnPoolsDict.Values
bool PathologicalGames.SpawnPoolsDict.IsReadOnly
bool ICollection<KeyValuePair<string , SpawnPool> >. PathologicalGames.SpawnPoolsDict.IsReadOnly
delegate void PathologicalGames.SpawnPoolsDict.OnCreatedDelegate(SpawnPool pool)
void PathologicalGames.SpawnPoolsDict.AddOnCreatedDelegate(string poolName, OnCreatedDelegate createdDelegate)
References PathologicalGames.SpawnPoolsDict.onCreatedDelegates.
void PathologicalGames.SpawnPoolsDict.RemoveOnCreatedDelegate(string poolName, OnCreatedDelegate createdDelegate)
References PathologicalGames.SpawnPoolsDict.onCreatedDelegates.
SpawnPool PathologicalGames.SpawnPoolsDict.Create(string poolName)
Creates a new GameObject with a SpawnPool Component which registers itself with the PoolManager.Pools dictionary. The SpawnPool can then be accessed directly via the return value of this function or by via the PoolManager.Pools dictionary using a 'key' (string : the name of the pool, SpawnPool.poolName).
poolName The name for the new SpawnPool. The GameObject will have the word "Pool" Added at the end. A reference to the new SpawnPool component
SpawnPool PathologicalGames.SpawnPoolsDict.Create(string poolName, GameObject owner)
Creates a SpawnPool Component on an 'owner' GameObject which registers itself with the PoolManager.Pools dictionary. The SpawnPool can then be accessed directly via the return value of this function or via the PoolManager.Pools dictionary.
poolName The name for the new SpawnPool. The GameObject will have the word "Pool" Added at the end. owner A GameObject to add the SpawnPool Component A reference to the new SpawnPool component
References PathologicalGames.SpawnPoolsDict.assertValidPoolName.
override string PathologicalGames.SpawnPoolsDict.ToString()
Returns a formatted string showing all the pool names
bool PathologicalGames.SpawnPoolsDict.Destroy(string poolName)
Destroy an entire SpawnPool, including its GameObject and all children. You can also just destroy the GameObject directly to achieve the same result. This is really only here to make it easier when a reference isn't at hand.
spawnPool
References PathologicalGames.SpawnPoolsDict._pools.
void PathologicalGames.SpawnPoolsDict.DestroyAll()
Destroy ALL SpawnPools, including their GameObjects and all children. You can also just destroy the GameObjects directly to achieve the same result. This is really only here to make it easier when a reference isn't at hand.
spawnPool
References PathologicalGames.SpawnPoolsDict._pools.
void PathologicalGames.SpawnPoolsDict.Add(string key, SpawnPool value)
bool PathologicalGames.SpawnPoolsDict.Remove(string poolName)
bool PathologicalGames.SpawnPoolsDict.ContainsKey(string poolName)
Returns true if a pool exists with the passed pool name.
poolName The name to look for True if the pool exists, otherwise, false.
Referenced by PathologicalGames.SpawnPoolsDict.Add, PathologicalGames.SpawnPoolsDict.assertValidPoolName, PathologicalGames.SpawnPoolsDict.Remove.
bool PathologicalGames.SpawnPoolsDict.TryGetValue(string poolName, out SpawnPool spawnPool)
Used to get a SpawnPool when the user is not sure if the pool name is used. This is faster than checking IsPool(poolName) and then accessing Pools][poolName.]
key value
bool PathologicalGames.SpawnPoolsDict.Contains(KeyValuePair< string, SpawnPool > item)
void PathologicalGames.SpawnPoolsDict.Add(KeyValuePair< string, SpawnPool > item)
void PathologicalGames.SpawnPoolsDict.Clear()
bool PathologicalGames.SpawnPoolsDict.Remove(KeyValuePair< string, SpawnPool > item)
IEnumerator<KeyValuePair<string , SpawnPool> > PathologicalGames.SpawnPoolsDict.GetEnumerator()
bool PathologicalGames.SpawnPoolsDict.assertValidPoolName(string poolName)
Used to ensure a name is valid before creating anything.
poolName The name to test True if sucessful, false if failed.
References PathologicalGames.SpawnPoolsDict.ContainsKey.
Referenced by PathologicalGames.SpawnPoolsDict.Create.
void PathologicalGames.SpawnPoolsDict.CopyTo(KeyValuePair< string, SpawnPool >[] array, int arrayIndex)
void ICollection<KeyValuePair<string , SpawnPool> >. PathologicalGames.SpawnPoolsDict.CopyTo(KeyValuePair< string, SpawnPool >[] array, int arrayIndex)
System.Collections.IEnumerator System.Collections.IEnumerable. PathologicalGames.SpawnPoolsDict.GetEnumerator()
void PathologicalGames.SpawnPoolsDict.Add(SpawnPool spawnPool)
Used internally by SpawnPools to add themseleves on Awake(). Use PoolManager.CreatePool() to create an entirely new SpawnPool GameObject
spawnPool
References PathologicalGames.SpawnPoolsDict.ContainsKey, PathologicalGames.SpawnPoolsDict.onCreatedDelegates, PathologicalGames.SpawnPool.poolName.
bool PathologicalGames.SpawnPoolsDict.Remove(SpawnPool spawnPool)
Used internally by SpawnPools to remove themseleves on Destroy(). Use PoolManager.Destroy() to destroy an entire SpawnPool GameObject.
spawnPool
References PathologicalGames.SpawnPoolsDict.ContainsKey, PathologicalGames.SpawnPool.poolName.