LitJson::JsonData
IList<JsonData> LitJson.JsonData.inst_array
Referenced by LitJson.JsonData.EnsureCollection, LitJson.JsonData.EnsureList, LitJson.JsonData.SetJsonType.
bool LitJson.JsonData.inst_boolean
Referenced by LitJson.JsonData.GetBoolean, LitJson.JsonData.JsonData, LitJson.JsonData.SetBoolean, LitJson.JsonData.SetJsonType.
double LitJson.JsonData.inst_double
Referenced by LitJson.JsonData.GetDouble, LitJson.JsonData.JsonData, LitJson.JsonData.SetDouble, LitJson.JsonData.SetJsonType.
int LitJson.JsonData.inst_int
Referenced by LitJson.JsonData.GetInt, LitJson.JsonData.JsonData, LitJson.JsonData.SetInt, LitJson.JsonData.SetJsonType.
long LitJson.JsonData.inst_long
Referenced by LitJson.JsonData.GetLong, LitJson.JsonData.JsonData, LitJson.JsonData.SetJsonType, LitJson.JsonData.SetLong.
IDictionary<string, JsonData> LitJson.JsonData.inst_object
Referenced by LitJson.JsonData.EnsureCollection, LitJson.JsonData.EnsureDictionary, LitJson.JsonData.SetJsonType.
string LitJson.JsonData.inst_string
Referenced by LitJson.JsonData.GetString, LitJson.JsonData.JsonData, LitJson.JsonData.SetJsonType, LitJson.JsonData.SetString, LitJson.JsonData.ToString.
string LitJson.JsonData.json
Referenced by LitJson.JsonData.Add, LitJson.JsonData.Clear, LitJson.JsonData.Insert, LitJson.JsonData.Remove, LitJson.JsonData.RemoveAt, LitJson.JsonData.SetBoolean, LitJson.JsonData.SetDouble, LitJson.JsonData.SetInt, LitJson.JsonData.SetLong, LitJson.JsonData.SetString, LitJson.JsonData.ToJson.
JsonType LitJson.JsonData.type
Referenced by LitJson.JsonData.EnsureCollection, LitJson.JsonData.EnsureDictionary, LitJson.JsonData.EnsureList, LitJson.JsonData.Equals, LitJson.JsonData.GetBoolean, LitJson.JsonData.GetDouble, LitJson.JsonData.GetInt, LitJson.JsonData.GetJsonType, LitJson.JsonData.GetLong, LitJson.JsonData.GetString, LitJson.JsonData.JsonData, LitJson.JsonData.operator Boolean, LitJson.JsonData.operator Double, LitJson.JsonData.operator Int32, LitJson.JsonData.operator Int64, LitJson.JsonData.operator String, LitJson.JsonData.SetBoolean, LitJson.JsonData.SetDouble, LitJson.JsonData.SetInt, LitJson.JsonData.SetJsonType, LitJson.JsonData.SetLong, LitJson.JsonData.SetString, LitJson.JsonData.ToString.
IList<KeyValuePair<string, JsonData> > LitJson.JsonData.object_list
Referenced by LitJson.JsonData.EnsureDictionary, LitJson.JsonData.GetEnumerator, LitJson.JsonData.Remove, LitJson.JsonData.RemoveAt, LitJson.JsonData.SetJsonType.
int LitJson.JsonData.Count
bool LitJson.JsonData.IsArray
Referenced by LitJson.JsonData.Clear.
bool LitJson.JsonData.IsBoolean
bool LitJson.JsonData.IsDouble
bool LitJson.JsonData.IsInt
bool LitJson.JsonData.IsLong
bool LitJson.JsonData.IsObject
Referenced by LitJson.JsonData.Clear.
bool LitJson.JsonData.IsString
int ICollection. LitJson.JsonData.Count
bool ICollection. LitJson.JsonData.IsSynchronized
object ICollection. LitJson.JsonData.SyncRoot
bool IDictionary. LitJson.JsonData.IsFixedSize
bool IDictionary. LitJson.JsonData.IsReadOnly
ICollection IDictionary. LitJson.JsonData.Keys
ICollection IDictionary. LitJson.JsonData.Values
bool IJsonWrapper. LitJson.JsonData.IsArray
bool IJsonWrapper. LitJson.JsonData.IsBoolean
bool IJsonWrapper. LitJson.JsonData.IsDouble
bool IJsonWrapper. LitJson.JsonData.IsInt
bool IJsonWrapper. LitJson.JsonData.IsLong
bool IJsonWrapper. LitJson.JsonData.IsObject
bool IJsonWrapper. LitJson.JsonData.IsString
bool IList. LitJson.JsonData.IsFixedSize
bool IList. LitJson.JsonData.IsReadOnly
object IDictionary. LitJson.JsonData.this[object key]
object IOrderedDictionary. LitJson.JsonData.this[int idx]
object IList. LitJson.JsonData.this[int index]
JsonData LitJson.JsonData.this[string prop_name]
JsonData LitJson.JsonData.this[int index]
LitJson.JsonData.JsonData()
Referenced by LitJson.JsonData.operator JsonData, LitJson.JsonData.ToJsonData.
LitJson.JsonData.JsonData(bool boolean)
References LitJson.JsonData.inst_boolean, LitJson.JsonData.type.
LitJson.JsonData.JsonData(double number)
References LitJson.JsonData.inst_double, LitJson.JsonData.type.
LitJson.JsonData.JsonData(int number)
References LitJson.JsonData.inst_int, LitJson.JsonData.type.
LitJson.JsonData.JsonData(long number)
References LitJson.JsonData.inst_long, LitJson.JsonData.type.
LitJson.JsonData.JsonData(object obj)
References LitJson.Boolean, LitJson.Double, LitJson.JsonData.inst_boolean, LitJson.JsonData.inst_double, LitJson.JsonData.inst_int, LitJson.JsonData.inst_long, LitJson.JsonData.inst_string, LitJson.String, LitJson.JsonData.type.
LitJson.JsonData.JsonData(string str)
References LitJson.JsonData.inst_string, LitJson.JsonData.type.
int LitJson.JsonData.Add(object value)
References LitJson.JsonData.EnsureList, LitJson.JsonData.json, LitJson.JsonData.ToJsonData.
void LitJson.JsonData.Clear()
References LitJson.JsonData.IsArray, LitJson.JsonData.IsObject.
bool LitJson.JsonData.Equals(JsonData x)
References LitJson.JsonData.type.
JsonType LitJson.JsonData.GetJsonType()
References LitJson.JsonData.type.
void LitJson.JsonData.SetJsonType(JsonType type)
References LitJson.Boolean, LitJson.Double, LitJson.JsonData.inst_array, LitJson.JsonData.inst_boolean, LitJson.JsonData.inst_double, LitJson.JsonData.inst_int, LitJson.JsonData.inst_long, LitJson.JsonData.inst_object, LitJson.JsonData.inst_string, LitJson.JsonData.object_list, LitJson.String, LitJson.JsonData.type.
string LitJson.JsonData.ToJson()
References LitJson.JsonData.json, LitJson.JsonData.WriteJson.
void LitJson.JsonData.ToJson(JsonWriter writer)
References LitJson.JsonData.WriteJson.
override string LitJson.JsonData.ToString()
References LitJson.JsonData.inst_string, LitJson.JsonData.type.
static implicit LitJson.JsonData.operator JsonData(Boolean data)
References LitJson.JsonData.JsonData.
static implicit LitJson.JsonData.operator JsonData(Double data)
References LitJson.JsonData.JsonData.
static implicit LitJson.JsonData.operator JsonData(Int32 data)
References LitJson.JsonData.JsonData.
static implicit LitJson.JsonData.operator JsonData(Int64 data)
References LitJson.JsonData.JsonData.
static implicit LitJson.JsonData.operator JsonData(String data)
References LitJson.JsonData.JsonData.
static LitJson.JsonData.operator Boolean(JsonData data)
References LitJson.JsonData.type.
static LitJson.JsonData.operator Double(JsonData data)
References LitJson.JsonData.type.
static LitJson.JsonData.operator Int32(JsonData data)
References LitJson.JsonData.type.
static LitJson.JsonData.operator Int64(JsonData data)
References LitJson.JsonData.type.
static LitJson.JsonData.operator String(JsonData data)
References LitJson.JsonData.type.
void ICollection. LitJson.JsonData.CopyTo(Array array, int index)
References LitJson.JsonData.EnsureCollection.
void IDictionary. LitJson.JsonData.Add(object key, object value)
References LitJson.JsonData.EnsureDictionary, LitJson.JsonData.json, LitJson.JsonData.ToJsonData.
Referenced by LitJson.JsonData.Add.
void IDictionary. LitJson.JsonData.Clear()
References LitJson.JsonData.EnsureDictionary, LitJson.JsonData.json.
bool IDictionary. LitJson.JsonData.Contains(object key)
References LitJson.JsonData.EnsureDictionary.
IDictionaryEnumerator IDictionary. LitJson.JsonData.GetEnumerator()
void IDictionary. LitJson.JsonData.Remove(object key)
References LitJson.JsonData.EnsureDictionary, LitJson.JsonData.json, LitJson.JsonData.object_list.
IEnumerator IEnumerable. LitJson.JsonData.GetEnumerator()
References LitJson.JsonData.EnsureCollection.
bool IJsonWrapper. LitJson.JsonData.GetBoolean()
References LitJson.JsonData.inst_boolean, LitJson.JsonData.type.
double IJsonWrapper. LitJson.JsonData.GetDouble()
References LitJson.JsonData.inst_double, LitJson.JsonData.type.
int IJsonWrapper. LitJson.JsonData.GetInt()
References LitJson.JsonData.inst_int, LitJson.JsonData.type.
long IJsonWrapper. LitJson.JsonData.GetLong()
References LitJson.JsonData.inst_long, LitJson.JsonData.type.
string IJsonWrapper. LitJson.JsonData.GetString()
References LitJson.JsonData.inst_string, LitJson.JsonData.type.
void IJsonWrapper. LitJson.JsonData.SetBoolean(bool val)
References LitJson.JsonData.inst_boolean, LitJson.JsonData.json, LitJson.JsonData.type.
void IJsonWrapper. LitJson.JsonData.SetDouble(double val)
References LitJson.JsonData.inst_double, LitJson.JsonData.json, LitJson.JsonData.type.
void IJsonWrapper. LitJson.JsonData.SetInt(int val)
References LitJson.JsonData.inst_int, LitJson.JsonData.json, LitJson.JsonData.type.
void IJsonWrapper. LitJson.JsonData.SetLong(long val)
References LitJson.JsonData.inst_long, LitJson.JsonData.json, LitJson.JsonData.type.
void IJsonWrapper. LitJson.JsonData.SetString(string val)
References LitJson.JsonData.inst_string, LitJson.JsonData.json, LitJson.JsonData.type.
string IJsonWrapper. LitJson.JsonData.ToJson()
Referenced by LitJson.JsonData.ToJson.
void IJsonWrapper. LitJson.JsonData.ToJson(JsonWriter writer)
References LitJson.JsonData.ToJson.
int IList. LitJson.JsonData.Add(object value)
References LitJson.JsonData.Add.
void IList. LitJson.JsonData.Clear()
References LitJson.JsonData.EnsureList, LitJson.JsonData.json.
bool IList. LitJson.JsonData.Contains(object value)
References LitJson.JsonData.EnsureList.
int IList. LitJson.JsonData.IndexOf(object value)
References LitJson.JsonData.EnsureList.
void IList. LitJson.JsonData.Insert(int index, object value)
References LitJson.JsonData.EnsureList, LitJson.JsonData.json.
void IList. LitJson.JsonData.Remove(object value)
References LitJson.JsonData.EnsureList, LitJson.JsonData.json.
void IList. LitJson.JsonData.RemoveAt(int index)
References LitJson.JsonData.EnsureList, LitJson.JsonData.json.
IDictionaryEnumerator IOrderedDictionary. LitJson.JsonData.GetEnumerator()
References LitJson.JsonData.EnsureDictionary, LitJson.JsonData.object_list.
void IOrderedDictionary. LitJson.JsonData.Insert(int idx, object key, object value)
References LitJson.JsonData.ToJsonData.
void IOrderedDictionary. LitJson.JsonData.RemoveAt(int idx)
References LitJson.JsonData.EnsureDictionary, LitJson.JsonData.object_list.
ICollection LitJson.JsonData.EnsureCollection()
References LitJson.JsonData.inst_array, LitJson.JsonData.inst_object, LitJson.JsonData.type.
Referenced by LitJson.JsonData.CopyTo, LitJson.JsonData.GetEnumerator.
IDictionary LitJson.JsonData.EnsureDictionary()
References LitJson.JsonData.inst_object, LitJson.JsonData.object_list, LitJson.JsonData.type.
Referenced by LitJson.JsonData.Add, LitJson.JsonData.Clear, LitJson.JsonData.Contains, LitJson.JsonData.GetEnumerator, LitJson.JsonData.Remove, LitJson.JsonData.RemoveAt.
IList LitJson.JsonData.EnsureList()
References LitJson.JsonData.inst_array, LitJson.JsonData.type.
Referenced by LitJson.JsonData.Add, LitJson.JsonData.Clear, LitJson.JsonData.Contains, LitJson.JsonData.IndexOf, LitJson.JsonData.Insert, LitJson.JsonData.Remove, LitJson.JsonData.RemoveAt.
JsonData LitJson.JsonData.ToJsonData(object obj)
References LitJson.JsonData.JsonData.
Referenced by LitJson.JsonData.Add, LitJson.JsonData.Insert.
static void LitJson.JsonData.WriteJson(IJsonWrapper obj, JsonWriter writer)
References LitJson.IJsonWrapper.IsArray, LitJson.IJsonWrapper.IsBoolean, LitJson.IJsonWrapper.IsDouble, LitJson.IJsonWrapper.IsInt, LitJson.IJsonWrapper.IsLong, LitJson.IJsonWrapper.IsObject, LitJson.IJsonWrapper.IsString.
Referenced by LitJson.JsonData.ToJson.