PathologicalGames::SpawnPool
List<GameObject> PathologicalGames.SpawnPool.prefabList
string PathologicalGames.SpawnPool.poolName
Returns the name of this pool used by PoolManager. This will always be the same as the name in Unity, unless the name contains the work "Pool", which PoolManager will strip out. This is done so you can name a prefab or GameObject in a way that is development friendly. For example, "EnemiesPool" is easier to understand than just "Enemies" when looking through a project.
Referenced by PathologicalGames.SpawnPoolsDict.Add, PathologicalGames.SpawnPool.Awake, PathologicalGames.SpawnPoolsDict.Remove.
bool PathologicalGames.SpawnPool.matchPoolScale
Matches new instances to the SpawnPool GameObject's scale.
Referenced by PathologicalGames.PrefabPool.SpawnNew.
bool PathologicalGames.SpawnPool.matchPoolLayer
Matches new instances to the SpawnPool GameObject's layer.
Referenced by PathologicalGames.PrefabPool.SpawnNew.
bool PathologicalGames.SpawnPool.dontReparent
If True, do not reparent instances under the SpawnPool's Transform.
Referenced by PathologicalGames.PrefabPool.SpawnNew.
bool PathologicalGames.SpawnPool._dontDestroyOnLoad
Referenced by PathologicalGames.SpawnPool.Awake.
bool PathologicalGames.SpawnPool.logMessages
Print information to the Unity Console
Referenced by PathologicalGames.SpawnPool.Add, PathologicalGames.SpawnPool.Awake, PathologicalGames.SpawnPool.CreatePrefabPool, PathologicalGames.SpawnPool.OnDestroy.
List<PrefabPool> PathologicalGames.SpawnPool._perPrefabPoolOptions
A list of PreloadDef options objects used by the inspector for user input
Referenced by LitFramework.LitPool.SpawnManager.AddPoolManager, PathologicalGames.SpawnPool.Awake.
Dictionary<object, bool> PathologicalGames.SpawnPool.prefabsFoldOutStates
Used by the inspector to store this instances foldout states.
float PathologicalGames.SpawnPool.maxParticleDespawnTime
The time in seconds to stop waiting for particles to die. A warning will be logged if this is triggered.
Referenced by PathologicalGames.SpawnPool.ListenForEmitDespawn.
PrefabsDict PathologicalGames.SpawnPool.prefabs
Returns the prefab of the given name (dictionary key)
Dictionary<object, bool> PathologicalGames.SpawnPool._editorListItemStates
bool PathologicalGames.SpawnPool.dontDestroyOnLoad
If true, the Pool's group, GameObject, will be set to Unity's Object.DontDestroyOnLoad()
Transform PathologicalGames.SpawnPool.group
The group is an empty game object which will be the parent of all instances in the pool. This helps keep the scene easy to work with.
Dictionary<string, PrefabPool> PathologicalGames.SpawnPool.prefabPools
Readonly access to prefab pools via a dictionary<string, PrefabPool>.
Transform PathologicalGames.SpawnPool.this[int index]
Read-only index access. You can still modify the instance at the given index. Read-only reffers to setting an index to a new instance reference, which would change the list. Setting via index is never needed to work with index access.
index int address of the item to get
int PathologicalGames.SpawnPool.Count
Returns the number of items in this (the collection). Readonly.
bool PathologicalGames.SpawnPool.IsReadOnly
List<PrefabPool> PathologicalGames.SpawnPool._prefabPools
Referenced by PathologicalGames.SpawnPool.Add, PathologicalGames.SpawnPool.Despawn, PathologicalGames.SpawnPool.GetPrefab, PathologicalGames.SpawnPool.GetPrefabPool, PathologicalGames.SpawnPool.OnDestroy.
List<Transform> PathologicalGames.SpawnPool._spawned
Referenced by PathologicalGames.SpawnPool.Despawn, PathologicalGames.SpawnPool.GetEnumerator, PathologicalGames.SpawnPool.ToString.
void PathologicalGames.SpawnPool.Awake()
References PathologicalGames.SpawnPool._dontDestroyOnLoad, PathologicalGames.SpawnPool._perPrefabPoolOptions, PathologicalGames.SpawnPool.logMessages, PathologicalGames.SpawnPool.poolName.
void PathologicalGames.SpawnPool.OnDestroy()
Runs when this group GameObject is destroyed and executes clean-up
References PathologicalGames.SpawnPool._prefabPools, PathologicalGames.SpawnPool.logMessages.
IEnumerator PathologicalGames.SpawnPool.DoDespawnAfterSeconds(Transform instance, float seconds, bool useParent, Transform parent)
Waits X seconds before despawning. See the docs for DespawnAfterSeconds() the argument useParent is used because a null parent is valid in Unity. It will make the scene root the parent
IEnumerator PathologicalGames.SpawnPool.ListForAudioStop(AudioSource src)
IEnumerator PathologicalGames.SpawnPool.ListenForEmitDespawn(ParticleEmitter emitter)
Used to determine when a particle emiter should be despawned
emitter ParticleEmitter to process
References PathologicalGames.SpawnPool.maxParticleDespawnTime.
Referenced by PathologicalGames.SpawnPool.Spawn.
IEnumerator PathologicalGames.SpawnPool.ListenForEmitDespawn(ParticleSystem emitter)
References PathologicalGames.PoolManagerUtils.activeInHierarchy, PathologicalGames.SpawnPool.maxParticleDespawnTime.
IEnumerator IEnumerable. PathologicalGames.SpawnPool.GetEnumerator()
Impliments the ability to use this list in a foreach loop
References PathologicalGames.SpawnPool._spawned.
bool ICollection<Transform>. PathologicalGames.SpawnPool.Remove(Transform item)
void PathologicalGames.SpawnPool.CreatePrefabPool(PrefabPool prefabPool)
Creates a new PrefabPool in this Pool and instances the requested number of instances (set by PrefabPool.preloadAmount). If preload amount is 0, nothing will be spawned and the return list will be empty.
It is rare this function is needed during regular usage. This function should only be used if you need to set the preferences of a new PrefabPool, such as culling or pre-loading, before use. Otherwise, just use Spawn() and if the prefab is used for the first time a PrefabPool will automatically be created with defaults anyway.Note: Instances with ParticleEmitters can be preloaded too because it won't trigger the emmiter or the coroutine which waits for particles to die, which Spawn() does.Usage Example: // Creates a prefab pool and sets culling options but doesn't // need to spawn any instances (this is fine) PrefabPool prefabPool = new PrefabPool() prefabPool.prefab = myPrefabReference; prefabPool.preloadAmount = 0; prefabPool.cullDespawned = True; prefabPool.cullAbove = 50; prefabPool.cullDelay = 30;// Enemies is just an example. Any pool is fine. PoolManager.Pools["Enemies"].CreatePrefabPool(prefabPool);// Then, just use as normal... PoolManager.Pools["Enemies"].Spawn(myPrefabReference); prefabPool A PrefabPool object A List of instances spawned or an empty List
References PathologicalGames.SpawnPool.logMessages, PathologicalGames.PrefabPool.preloaded.
void PathologicalGames.SpawnPool.Add(Transform instance, string prefabName, bool despawn, bool parent)
Add an existing instance to this pool. This is used during game start to pool objects which are not instanciated at runtime
instance The instance to add prefabName The name of the prefab used to create this instance despawn True to depawn on start parent True to make a child of the pool's group
References PathologicalGames.SpawnPool._prefabPools, PathologicalGames.SpawnPool.logMessages.
void PathologicalGames.SpawnPool.Add(Transform item)
Not Implimented. Use Spawn() to properly add items to the pool. This is required because the prefab needs to be stored in the internal data structure in order for the pool to function properly. Items can only be added by instencing them using SpawnInstance().
item
void PathologicalGames.SpawnPool.Remove(Transform item)
Not Implimented. Use Despawn() to properly manage items that should remain in the Queue but be deactivated. There is currently no way to safetly remove items from the pool permentantly. Destroying Objects would defeat the purpose of the pool.
item
Transform PathologicalGames.SpawnPool.Spawn(Transform prefab, Vector3 pos, Quaternion rot, Transform parent)
Spawns an instance or creates a new instance if none are available. Either way, an instance will be set to the passed position and rotation.Detailed Information: Checks the Data structure for an instance that was already created using the prefab. If the prefab has been used before, such as by setting it in the Unity Editor to preload instances, or just used before via this function, one of its instances will be used if one is available, or a new one will be created.If the prefab has never been used a new PrefabPool will be started with default options.To alter the options on a prefab pool, use the Unity Editor or see the documentation for the PrefabPool class and SpawnPool.SpawnPrefabPool()Broadcasts "OnSpawned" to the instance. Use this to manage states.An overload of this function has the same initial signature as Unity's Instantiate() that takes position and rotation. The return Type is different though. Unity uses and returns a GameObject reference. PoolManager uses and returns a Transform reference (or other supported type, such as AudioSource and ParticleSystem) prefab The prefab used to spawn an instance. Only used for reference if an instance is already in the pool and available for respawn. NOTE: Type = Transform pos The position to set the instance to rot The rotation to set the instance to parent An optional parent for the instance The instance's Transform.If the Limit option was used for the PrefabPool associated with the passed prefab, then this method will return null if the limit is reached. You DO NOT need to test for null return values unless you used the limit option.
Referenced by PathologicalGames.SpawnPool.Spawn.
Transform PathologicalGames.SpawnPool.Spawn(Transform prefab, Vector3 pos, Quaternion rot)
See primary Spawn method for documentation.
Transform PathologicalGames.SpawnPool.Spawn(Transform prefab)
See primary Spawn method for documentation.
Overload to take only a prefab and instance using an 'empty' position and rotation.
Transform PathologicalGames.SpawnPool.Spawn(Transform prefab, Transform parent)
See primary Spawn method for documentation.
Convienince overload to take only a prefab and parent the new instance under the given parent
Transform PathologicalGames.SpawnPool.Spawn(string prefabName)
See primary Spawn method for documentation.
Overload to take only a prefab name. The cached reference is pulled from the SpawnPool.prefabs dictionary.
Transform PathologicalGames.SpawnPool.Spawn(string prefabName, Transform parent)
See primary Spawn method for documentation.
Convienince overload to take only a prefab name and parent the new instance under the given parent
Transform PathologicalGames.SpawnPool.Spawn(string prefabName, Vector3 pos, Quaternion rot)
See primary Spawn method for documentation.
Overload to take only a prefab name. The cached reference is pulled from the SpawnPool.prefabs dictionary. An instance will be set to the passed position and rotation.
Transform PathologicalGames.SpawnPool.Spawn(string prefabName, Vector3 pos, Quaternion rot, Transform parent)
See primary Spawn method for documentation.
Convienince overload to take only a prefab name and parent the new instance under the given parent. An instance will be set to the passed position and rotation.
AudioSource PathologicalGames.SpawnPool.Spawn(AudioSource prefab, Vector3 pos, Quaternion rot)
AudioSource PathologicalGames.SpawnPool.Spawn(AudioSource prefab)
AudioSource PathologicalGames.SpawnPool.Spawn(AudioSource prefab, Transform parent)
AudioSource PathologicalGames.SpawnPool.Spawn(AudioSource prefab, Vector3 pos, Quaternion rot, Transform parent)
References PathologicalGames.SpawnPool.Spawn.
ParticleSystem PathologicalGames.SpawnPool.Spawn(ParticleSystem prefab, Vector3 pos, Quaternion rot)
See docs for SpawnInstance(Transform prefab, Vector3 pos, Quaternion rot) for basic functionalty information.
Pass a ParticleSystem component of a prefab to instantiate, trigger emit, then listen for when all particles have died to "auto-destruct", but instead of destroying the game object it will be deactivated and added to the pool to be reused.IMPORTANT: You must pass a ParticleSystem next time as well, or the emitter will be treated as a regular prefab and simply activate, but emit will not be triggered!The listner that waits for the death of all particles will time-out after a set number of seconds and log a warning. This is done to keep the developer aware of any unexpected usage cases. Change the public property "maxParticleDespawnTime" to adjust this length of time. Broadcasts "OnSpawned" to the instance. Use this instead of Awake()This function has the same initial signature as Unity's Instantiate() that takes position and rotation. The return Type is different though.
References PathologicalGames.SpawnPool.Spawn.
ParticleSystem PathologicalGames.SpawnPool.Spawn(ParticleSystem prefab, Vector3 pos, Quaternion rot, Transform parent)
See primary Spawn ParticleSystem method for documentation.
Convienince overload to take only a prefab name and parent the new instance under the given parent. An instance will be set to the passed position and rotation.
ParticleEmitter PathologicalGames.SpawnPool.Spawn(ParticleEmitter prefab, Vector3 pos, Quaternion rot)
See docs for SpawnInstance(ParticleSystems prefab, Vector3 pos, Quaternion rot) This is the same but for ParticleEmitters
IMPORTANT: This function turns off Unity's ParticleAnimator autodestruct if one is found.
ParticleEmitter PathologicalGames.SpawnPool.Spawn(ParticleEmitter prefab, Vector3 pos, Quaternion rot, string colorPropertyName, Color color)
This will not be supported for Shuriken particles. This will eventually be depricated.
prefab The prefab to instance. Not used if an instance already exists in the scene that is queued for reuse. Type = ParticleEmitter pos The position to set the instance to rot The rotation to set the instance to colorPropertyName Same as Material.SetColor() color a Color object. Same as Material.SetColor() The instance's ParticleEmitter
References PathologicalGames.SpawnPool.ListenForEmitDespawn.
void PathologicalGames.SpawnPool.Despawn(Transform instance)
If the passed object is managed by the SpawnPool, it will be deactivated and made available to be spawned again.
Despawned instances are removed from the primary list. item The transform of the gameobject to process
References PathologicalGames.SpawnPool._prefabPools, PathologicalGames.SpawnPool._spawned.
Referenced by PathologicalGames.SpawnPool.DespawnAll.
void PathologicalGames.SpawnPool.Despawn(Transform instance, Transform parent)
See docs for Despawn(Transform instance) for basic functionalty information.
Convienince overload to provide the option to re-parent for the instance just before despawn.
void PathologicalGames.SpawnPool.Despawn(Transform instance, float seconds)
See docs for Despawn(Transform instance). This expands that functionality. If the passed object is managed by this SpawnPool, it will be deactivated and made available to be spawned again. item The transform of the instance to process seconds The time in seconds to wait before despawning
void PathologicalGames.SpawnPool.Despawn(Transform instance, float seconds, Transform parent)
See docs for Despawn(Transform instance) for basic functionalty information.
Convienince overload to provide the option to re-parent for the instance just before despawn.
void PathologicalGames.SpawnPool.DespawnAll()
Despawns all active instances in this SpawnPool
References PathologicalGames.SpawnPool.Despawn.
bool PathologicalGames.SpawnPool.IsSpawned(Transform instance)
Returns true if the passed transform is currently spawned. item The transform of the gameobject to test
PrefabPool PathologicalGames.SpawnPool.GetPrefabPool(Transform prefab)
Returns the prefab pool for a given prefab.
prefab The Transform of an instance PrefabPool
PrefabPool PathologicalGames.SpawnPool.GetPrefabPool(GameObject prefab)
Returns the prefab pool for a given prefab.
prefab The GameObject of an instance PrefabPool
References PathologicalGames.SpawnPool._prefabPools.
Transform PathologicalGames.SpawnPool.GetPrefab(Transform instance)
Returns the prefab used to create the passed instance. This is provided for convienince as Unity doesn't offer this feature.
instance The Transform of an instance Transform
References PathologicalGames.SpawnPool._prefabPools, PathologicalGames.SpawnPool.Contains.
GameObject PathologicalGames.SpawnPool.GetPrefab(GameObject instance)
Returns the prefab used to create the passed instance. This is provided for convienince as Unity doesn't offer this feature.
instance The GameObject of an instance GameObject
References PathologicalGames.SpawnPool._prefabPools, PathologicalGames.SpawnPool.Contains.
override string PathologicalGames.SpawnPool.ToString()
Returns a formatted string showing all the spawned member names
References PathologicalGames.SpawnPool._spawned.
bool PathologicalGames.SpawnPool.Contains(Transform item)
The name "Contains" is misleading so IsSpawned was implimented instead.
item
Referenced by PathologicalGames.SpawnPool.GetPrefab.
void PathologicalGames.SpawnPool.CopyTo(Transform[] array, int arrayIndex)
Used by OTHERList.AddRange() This adds this list to the passed list
array The list AddRange is being called on arrayIndex The starting index for the copy operation. AddRange seems to pass the last index.
IEnumerator<Transform> PathologicalGames.SpawnPool.GetEnumerator()
Impliments the ability to use this list in a foreach loop
References PathologicalGames.SpawnPool._spawned.
int PathologicalGames.SpawnPool.IndexOf(Transform item)
void PathologicalGames.SpawnPool.Insert(int index, Transform item)
void PathologicalGames.SpawnPool.RemoveAt(int index)
void PathologicalGames.SpawnPool.Clear()