LitJson::JsonMapper
int LitJson.JsonMapper.max_nesting_depth
Referenced by LitJson.JsonMapper.JsonMapper, LitJson.JsonMapper.WriteValue.
IFormatProvider LitJson.JsonMapper.datetime_format
Referenced by LitJson.JsonMapper.JsonMapper, LitJson.JsonMapper.RegisterBaseExporters, LitJson.JsonMapper.RegisterBaseImporters.
IDictionary<Type, ExporterFunc> LitJson.JsonMapper.base_exporters_table
Referenced by LitJson.JsonMapper.JsonMapper, LitJson.JsonMapper.RegisterBaseExporters, LitJson.JsonMapper.WriteValue.
IDictionary<Type, ExporterFunc> LitJson.JsonMapper.custom_exporters_table
Referenced by LitJson.JsonMapper.JsonMapper, LitJson.JsonMapper.RegisterExporter< T >, LitJson.JsonMapper.WriteValue.
IDictionary<Type, IDictionary<Type, ImporterFunc> > LitJson.JsonMapper.base_importers_table
Referenced by LitJson.JsonMapper.JsonMapper, LitJson.JsonMapper.ReadValue, LitJson.JsonMapper.RegisterBaseImporters.
IDictionary<Type, IDictionary<Type, ImporterFunc> > LitJson.JsonMapper.custom_importers_table
Referenced by LitJson.JsonMapper.JsonMapper, LitJson.JsonMapper.ReadValue, LitJson.JsonMapper.RegisterImporter< TJson, TValue >.
IDictionary<Type, ArrayMetadata> LitJson.JsonMapper.array_metadata
Referenced by LitJson.JsonMapper.AddArrayMetadata, LitJson.JsonMapper.JsonMapper, LitJson.JsonMapper.ReadValue.
readonly object LitJson.JsonMapper.array_metadata_lock
Referenced by LitJson.JsonMapper.AddArrayMetadata.
IDictionary<Type, IDictionary<Type, MethodInfo> > LitJson.JsonMapper.conv_ops
Referenced by LitJson.JsonMapper.GetConvOp, LitJson.JsonMapper.JsonMapper.
readonly object LitJson.JsonMapper.conv_ops_lock
Referenced by LitJson.JsonMapper.GetConvOp.
IDictionary<Type, ObjectMetadata> LitJson.JsonMapper.object_metadata
Referenced by LitJson.JsonMapper.AddObjectMetadata, LitJson.JsonMapper.JsonMapper, LitJson.JsonMapper.ReadValue.
readonly object LitJson.JsonMapper.object_metadata_lock
Referenced by LitJson.JsonMapper.AddObjectMetadata.
IDictionary<Type, IList<PropertyMetadata> > LitJson.JsonMapper.type_properties
Referenced by LitJson.JsonMapper.AddTypeProperties, LitJson.JsonMapper.JsonMapper, LitJson.JsonMapper.WriteValue.
readonly object LitJson.JsonMapper.type_properties_lock
Referenced by LitJson.JsonMapper.AddTypeProperties.
JsonWriter LitJson.JsonMapper.static_writer
Referenced by LitJson.JsonMapper.JsonMapper, LitJson.JsonMapper.ToJson.
readonly object LitJson.JsonMapper.static_writer_lock
Referenced by LitJson.JsonMapper.ToJson.
static LitJson.JsonMapper.JsonMapper()
References LitJson.JsonMapper.array_metadata, LitJson.JsonMapper.base_exporters_table, LitJson.JsonMapper.base_importers_table, LitJson.JsonMapper.conv_ops, LitJson.JsonMapper.custom_exporters_table, LitJson.JsonMapper.custom_importers_table, LitJson.JsonMapper.datetime_format, LitJson.JsonMapper.max_nesting_depth, LitJson.JsonMapper.object_metadata, LitJson.JsonMapper.RegisterBaseExporters, LitJson.JsonMapper.RegisterBaseImporters, LitJson.JsonMapper.static_writer, LitJson.JsonMapper.type_properties.
static void LitJson.JsonMapper.AddArrayMetadata(Type type)
References LitJson.JsonMapper.array_metadata, LitJson.JsonMapper.array_metadata_lock, LitJson.ArrayMetadata.ElementType, LitJson.ArrayMetadata.IsList.
Referenced by LitJson.JsonMapper.ReadValue.
static void LitJson.JsonMapper.AddObjectMetadata(Type type)
References LitJson.ObjectMetadata.IsDictionary, LitJson.JsonMapper.object_metadata, LitJson.JsonMapper.object_metadata_lock, LitJson.ObjectMetadata.Properties.
Referenced by LitJson.JsonMapper.ReadValue.
static void LitJson.JsonMapper.AddTypeProperties(Type type)
References LitJson.JsonMapper.type_properties, LitJson.JsonMapper.type_properties_lock.
Referenced by LitJson.JsonMapper.WriteValue.
static MethodInfo LitJson.JsonMapper.GetConvOp(Type t1, Type t2)
References LitJson.JsonMapper.conv_ops, LitJson.JsonMapper.conv_ops_lock.
Referenced by LitJson.JsonMapper.ReadValue.
static object LitJson.JsonMapper.ReadValue(Type inst_type, JsonReader reader)
References LitJson.JsonMapper.AddArrayMetadata, LitJson.JsonMapper.AddObjectMetadata, LitJson.Array, LitJson.JsonMapper.array_metadata, LitJson.JsonMapper.base_importers_table, LitJson.JsonMapper.custom_importers_table, LitJson.ObjectMetadata.ElementType, LitJson.JsonMapper.GetConvOp, LitJson.ImporterFunc, LitJson.PropertyMetadata.Info, LitJson.ArrayMetadata.IsArray, LitJson.ObjectMetadata.IsDictionary, LitJson.PropertyMetadata.IsField, LitJson.ArrayMetadata.IsList, LitJson.JsonMapper.object_metadata, LitJson.ObjectMetadata.Properties, LitJson.JsonMapper.ReadSkip, LitJson.JsonReader.SkipNonMembers, LitJson.String, LitJson.JsonReader.Token, LitJson.PropertyMetadata.Type, LitJson.JsonReader.Value.
Referenced by LitJson.JsonMapper.ReadValue, LitJson.JsonMapper.ToObject< T >, LitJson.JsonMapper.ToWrapper.
static IJsonWrapper LitJson.JsonMapper.ReadValue(WrapperFactory factory, JsonReader reader)
References LitJson.JsonMapper.ReadValue, LitJson.JsonReader.Token, LitJson.JsonReader.Value.
static void LitJson.JsonMapper.ReadSkip(JsonReader reader)
References LitJson.JsonMapper.ToWrapper.
Referenced by LitJson.JsonMapper.ReadValue.
static void LitJson.JsonMapper.RegisterBaseExporters()
References LitJson.JsonMapper.base_exporters_table, LitJson.JsonMapper.datetime_format.
Referenced by LitJson.JsonMapper.JsonMapper.
static void LitJson.JsonMapper.RegisterBaseImporters()
References LitJson.JsonMapper.base_importers_table, LitJson.JsonMapper.datetime_format, LitJson.ImporterFunc, LitJson.JsonMapper.RegisterImporter.
Referenced by LitJson.JsonMapper.JsonMapper.
static void LitJson.JsonMapper.RegisterImporter(IDictionary< Type, IDictionary< Type, ImporterFunc >> table, Type json_type, Type value_type, ImporterFunc importer)
Referenced by LitJson.JsonMapper.RegisterBaseImporters, LitJson.JsonMapper.RegisterImporter< TJson, TValue >.
static void LitJson.JsonMapper.WriteValue(object obj, JsonWriter writer, bool writer_is_private, int depth)
References LitJson.JsonMapper.AddTypeProperties, LitJson.Array, LitJson.JsonMapper.base_exporters_table, LitJson.Boolean, LitJson.JsonMapper.custom_exporters_table, LitJson.Double, LitJson.ExporterFunc, LitJson.PropertyMetadata.Info, LitJson.PropertyMetadata.IsField, LitJson.JsonMapper.max_nesting_depth, LitJson.String, LitJson.JsonMapper.type_properties, LitJson.JsonWriter.Write.
Referenced by LitJson.JsonMapper.ToJson.
static string LitJson.JsonMapper.ToJson(object obj)
References LitJson.JsonMapper.static_writer, LitJson.JsonMapper.static_writer_lock, LitJson.JsonMapper.WriteValue.
static void LitJson.JsonMapper.ToJson(object obj, JsonWriter writer)
References LitJson.JsonMapper.WriteValue.
static JsonData LitJson.JsonMapper.ToObject(JsonReader reader)
References LitJson.JsonMapper.ToWrapper.
static JsonData LitJson.JsonMapper.ToObject(TextReader reader)
References LitJson.JsonMapper.ToWrapper.
static JsonData LitJson.JsonMapper.ToObject(string json)
References LitJson.JsonMapper.ToWrapper.
static T LitJson.JsonMapper.ToObject< T >(JsonReader reader)
References LitJson.JsonMapper.ReadValue.
static T LitJson.JsonMapper.ToObject< T >(TextReader reader)
References LitJson.JsonMapper.ReadValue.
static T LitJson.JsonMapper.ToObject< T >(string json)
References LitJson.JsonMapper.ReadValue.
static IJsonWrapper LitJson.JsonMapper.ToWrapper(WrapperFactory factory, JsonReader reader)
References LitJson.JsonMapper.ReadValue.
Referenced by LitJson.JsonMapper.ReadSkip, LitJson.JsonMapper.ToObject.
static IJsonWrapper LitJson.JsonMapper.ToWrapper(WrapperFactory factory, string json)
References LitJson.JsonMapper.ReadValue.
static void LitJson.JsonMapper.RegisterExporter< T >(ExporterFunc< T > exporter)
References LitJson.JsonMapper.custom_exporters_table, LitJson.ExporterFunc.
static void LitJson.JsonMapper.RegisterImporter< TJson, TValue >(ImporterFunc< TJson, TValue > importer)
References LitJson.JsonMapper.custom_importers_table, LitJson.ImporterFunc, LitJson.JsonMapper.RegisterImporter.
static void LitJson.JsonMapper.UnregisterExporters()
static void LitJson.JsonMapper.UnregisterImporters()